spring:
  application:
    name: order-service
  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true
    stream:
      kafka:
        binder:
          brokers: "localhost:9092"

server:
  port: 8082

eureka:
  client:
    enabled: true
    registry-fetch-interval-seconds: 10
    initial-instance-info-replication-interval-seconds: 10
  instance:
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

order-type: express
