
spring:
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/reda-jaifar/spring-config-server-repository.git'
          clone-on-start: true
          search-paths: 'config/{application}'
    stream:
      kafka:
        binder:
          brokers: "localhost:9092"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
    registry-fetch-interval-seconds: 10
    initial-instance-info-replication-interval-seconds: 10
  instance:
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10

server:
  port: 8888
